### ISSUE TITLE
Feature Request - Port Item Sets from Old Structure to New

### ISSUE THREAD

**Issue by BobT36** [Cadrach/lol_ise#39]
Issue Described here: https://boards.na.leagueoflegends.com/en/c/alpha-client-discussion/G71fNgKl-porting-item-sets-to-new-client

Require the ability to provide the old ItemSets.json file, and have it be separated out into the new structure (folders per champion etc).

In the attached ItemSets.json file, I have item sets specific to a single champion, and some that are shared by multiple champions. None set per map though. I'd like to be able to recover them and port them to the new structure, (successful example with the included Garen folder, where I loaded him on the old client, before it was disabled.). 

[Item Sets.zip](https://github.com/Cadrach/lol_ise/files/981723/Item.Sets.zip)

**Comment by Cadrach** [comment]
Hi,

I was able to modify the code so that it can analyse & load this file. It also keeps the sharing structure (so modifying one set will modify the others it is shared with)

I will not push this feature on the live site, because it creates duplicates of your sets: basically, sets found in this file can already be deployed in their champion's folder, which creates a big mess.

I may later on, if it becomes a thing, add it with a warning message like "loading legacy sets, are you sure?", but I think it will lead to problems any way.

You will find your generated folders fome the **ItemSets.json** file in the zip below:

[BobT_ItemSets.zip](https://github.com/Cadrach/lol_ise/files/981801/BobT_ItemSets.zip)

**Comment by BobT36** [comment]
Works amazingly. Thanks a lot! You've saved me a LOT of time. 

Might be worth adding though, just with a warning to people to back up their existing Champions folder if they use it. 

Of course it would just be a one-time use thing but even then if many people like me have a LOT of item sets that they can't get access to now, they'd appreciate being able to salvage them.

Just shows Riot could have done the same, if they could be bothered. 

Either way that's just what I wanted. Thankyou!
