### ISSUE TITLE
Each time I install a new item set, it overwrites the in-game hotkeys

### ISSUE THREAD

**Issue by mjeung** [Cadrach/lol_ise#43]
Steps to reproduce:

1. Set up some custom hot-keys in game.
2. Upload /Config directory to online Item Set Editor
3. Make changes using web interface.
4. Download and install new item set.
5. Custom hot-keys from step 1 no longer set.

**Comment by Cadrach** [comment]
Are you on Mac?

**Comment by mjeung** [comment]
No, PC.

**Comment by mjeung** [comment]
(Am I the only one who encounters this problem?  Hopefully not.  If you can't reproduce, let me know and I'll test it out again.)

**Comment by Cadrach** [comment]
It is not that, but basically what happens is your are somehow deleting the files that are in the root of the Config folder. If you are simply deploying the Config folder by replacing it, it should merge it to your existing files (except on Mac where it would replace it completely)

So my next question is: When you deploy the set, are you deleting completely your previous Config folder? If so you should not, you simply have to paste the one from the .zip file so that it merges with the existing one.

Let me know!

**Comment by mjeung** [comment]
Ah. That explains it.  I was moving my Config folder out of the way and replacing it wholesale with the contents of the .zip file.    

The readme file says "Use this folder to replace the Config/ folder in your League of Legends installation" - so I thought I was doing the right thing -- But now I understand that I should deploy into the existing Config folder.

Thanks!

**Comment by Cadrach** [comment]
You're welcome, have fun!
