### ISSUE TITLE
Import old sets from "ItemSets.json" file

### ISSUE THREAD

**Issue by AR4nd0mGuy** [Cadrach/lol_ise#44]
In the Config foulder of my game I have a file called "ItemSets.json". It contains every item set I made in the legacy client. In first the title and things like associated Champions and Maps are declared and the blocks with their names and their items (items are there as ID) are spelled out. would it be possible for you to come up with a fifth uploading option that lets me use my old item sets and converts them into kind.
[ItemSets.zip](https://github.com/Cadrach/lol_ise/files/1016781/ItemSets.zip)

**Comment by Cadrach** [comment]
Hi,

This was asked before, and I have refrained from doing it because it may lead to duplicates if you have both the old file & some deployed sets.

However, I have a local fix, and can & have generated the folders for you:
![image](https://cloud.githubusercontent.com/assets/142103/26317285/41d81154-3f17-11e7-910f-598fee3c9c4f.png)

Download link: https://we.tl/OWeUGWgJex
